#ifndef CHECKPOINTSTORE_BASE_VERSION_HPP
#define CHECKPOINTSTORE_BASE_VERSION_HPP

#define CHECKPOINTSTORE_VERSION_MAJOR 1
#define CHECKPOINTSTORE_VERSION_MINOR 0
#define CHECKPOINTSTORE_VERSION_PATCH 0

#endif
